### ISSUE TITLE
discrimination-0.4 fails to build with GHC 9.0.1 and 9.2.1

### ISSUE THREAD

**Issue by sjakobi** [ekmett/discrimination#42]
```
src/Data/Discrimination/Grouping.hs:169:100: warning: [-Wdeprecations]
    In the use of ‘sizeInBaseInteger’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerSizeInBase# instead"
    |
169 |   p@(MutablePrimArray mba) :: MutablePrimArray RealWorld Word8 <- newPrimArray (fromIntegral $ W# (sizeInBaseInteger i 256#))
    |                                                                                                    ^^^^^^^^^^^^^^^^^

src/Data/Discrimination/Grouping.hs:170:8: warning: [-Wdeprecations]
    In the use of ‘exportIntegerToMutableByteArray’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerToMutableByteArray# instead"
    |
170 |   _ <- exportIntegerToMutableByteArray i mba 0## 1#
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[5 of 7] Compiling Data.Discrimination.Sorting ( src/Data/Discrimination/Sorting.hs, dist/build/Data/Discrimination/Sorting.o, dist/build/Data/Discrimination/Sorting.dyn_o )
[6 of 7] Compiling Data.Discrimination.Class ( src/Data/Discrimination/Class.hs, dist/build/Data/Discrimination/Class.o, dist/build/Data/Discrimination/Class.dyn_o )

src/Data/Discrimination/Class.hs:23:10: error:
    • Couldn't match type: forall b1. [(a, b1)] -> [[b1]]
                     with: [(a, b)] -> [[b]]
      Expected: Sort a -> [(a, b)] -> [[b]]
        Actual: Sort a -> forall b. [(a, b)] -> [[b]]
    • In the expression: runSort
      In an equation for ‘disc’: disc = runSort
      In the instance declaration for ‘Discriminating Sort’
    • Relevant bindings include
        disc :: Sort a -> [(a, b)] -> [[b]]
          (bound at src/Data/Discrimination/Class.hs:23:3)
   |
23 |   disc = runSort
   |          ^^^^^^^
cabal: Failed to build discrimination-0.4.
```

Possibly related to simplified subsumption?!

As a Hackage trustee, I've revised v0.4 to prevent users from encountering this error: https://hackage.haskell.org/package/discrimination-0.4/revisions/

**Comment by sjakobi** [comment]
In order to properly support building with GHC 9.2.1, you'd need to relax the bound on `ghc-bignum` BTW.

**Comment by RyanGlScott** [comment]
Thanks for spotting this.

The latest Hackage release of `discrimination` (0.4.1) fixes the `runSort` issue (see 93b73514368ff6517543b3151e6f442b7b94ed51) and the `ghc-bignum` issues (see 02c0bad26926a9352086ba47ad7d08a0d477612f), so I don't think there's anything to be done for 9.0.1. For 9.2.1, the current `ghc-bignum` upper bounds are indeed too restrictive. I'll prepare a patch to relax them momentarily.

**Comment by RyanGlScott** [comment]
I've made a [corresponding revision](https://hackage.haskell.org/package/discrimination-0.4.1/revisions/) on Hackage.
